include theme.conf

term xterm-256color
window_padding_width 3
window_margin_width 5
hide_window_decorations yes
background_opacity 1
dynamic_background_opacity yes

blur_radius 20
font_family JetBrainsMono Nerd Font
font_size 16

confirm_os_window_close 0
allow_hyperlinks yes
scrollback_lines 10000
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 1.0
enable_audio_bell no
visual_bell_duration 0.0

cursor_blink_interval 0
cursor_stop_blinking_after 15.0
cursor_shape block
cursor_beam_thickness 1.5
cursor_trail_decay 0.1 0.4
cursor_trail 1 
url_style curly

shell zsh
shell_integration disabled

allow_remote_control no
listen_on none
enabled_layouts *
focus_follows_mouse no
tab_bar_style hidden

repaint_delay 10
input_delay 0
sync_to_monitor yes
mouse_hide_wait 0
remember_window_size no
scrollback_handle_opacity 0 
scrollback_track_opacity 0 
scrollback_track_hover_opacity 0

map ctrl+shift+t no_op
map ctrl+shift+w no_op
map ctrl+shift+right no_op
map ctrl+shift+left no_op
