# vim:set ft=sh

MODULES=(btrfs i915 nvidia nvidia_modeset nvidia_uvm nvidia_drm)

BINARIES=(/usr/bin/btrfs)

FILES=()

HOOKS=(base udev plymouth autodetect microcode modconf kms keyboard keymap consolefont block filesystems fsck)

COMPRESSION="zstd"
COMPRESSION_OPTIONS=("-19" "--long" "--ultra")
