mdns all
detect-captive-portals false
hardened-privacy false
max-inflight-requests 256
report-client-info true
setup-router true
auto-activate true
profile d6859c
max-ttl 5s
use-hosts true
timeout 5s
debug false
control /var/run/nextdns.sock
log-queries false
cache-size 10MB
bogus-priv true
listen localhost:53
cache-max-age 0s
discovery-dns 
