#!/bin/bash

# Hyprpicker çıktısını al, sadece '#' ile başlayan satırı seç ve satır başını kaldır
COLOR=$(hyprpicker | grep '^#' | tr -d '\n')

if [ -n "$COLOR" ]; then
    echo -n "$COLOR" | wl-copy
    notify-send -u normal "🎨 Color Picked" "Copied to clipboard: <b>$COLOR</b>" --icon=applications-graphics
fi

