return function()
    hl.on("hyprland.start", function()
        hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
        hl.exec_cmd("waybar & awww-daemon & swaync")
        hl.exec_cmd("wl-clipboard-history -t ; wl-paste --type text --watch cliphist store ; wl-paste --type image --watch cliphist store ; wl-clip-persist --clipboard regular --display wayland")
        hl.exec_cmd("hyprctl plugin load ~/.config/hypr/modules/plugins/hyprselect.so")
        hl.exec_cmd("foot --server")
        hl.exec_cmd("ollama serve")
        hl.exec_cmd("hyprpm reload")
        hl.exec_cmd("hyprsunset")
    end)
end
