return function()
    hl.env("HYPRCURSOR_SIZE", "24")
    hl.env("HYPRCURSOR_THEME", "Catppuccin-Mocha-Dark-Cursors")
    hl.env("WAYLAND_DISPLAY", "wayland-1")
    hl.env("GDK_BACKEND", "wayland,x11,*")
    hl.env("QT_QPA_PLATFORM", "wayland;xcb")
    hl.env("SDL_VIDEODRIVER", "wayland")
    hl.env("CLUTTER_BACKEND", "wayland")
    hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
    hl.env("XDG_SESSION_TYPE", "wayland")
    hl.env("XDG_SESSION_DESKTOP", "Hyprland")
    hl.env("MOZ_ENABLE_WAYLAND", "1")
    hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
    hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
end
