#-- General --#
general {
    gaps_in = 5 
    gaps_out = 20

    border_size = 3 
    col.active_border = $Accent
    col.inactive_border = $Background


    resize_on_border = false

    allow_tearing = true
}
