##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    name = pavucontrol 
    match:class = org.pulseaudio.pavucontrol
    
    float = on
    size = 500, 300
    move = -520 50
    border_size = 0
    animation = slidedown
    pin = on
}

layerrule {
    name = rofi
    match:namespace = rofi
    dim_around = on
    animation = popin 85%
}


layerrule {
    name = wlogout
    match:namespace = logout_dialog 
    dim_around = on
    blur = on
    animation = popin 85%
}

layerrule {
    name = swaync-control-center
    match:namespace = swaync-control-center
    blur = on
    animation = slide right 60%
    ignore_alpha = 0.5
    xray = 0
}

layerrule {
    name = swaync-notifications
    match:namespace = swaync-notification-window
    blur = on
    animation = slide right 60%
    ignore_alpha = 0.5
    xray = 0
}
