##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    name = satty
    match:class = com.gabm.satty
    float = true
    size = 500 600
    center = true
    opacity = 1
    dim_around = true
}


layerrule {
    name = rofi
    match:namespace = rofi
    dim_around = on
    animation = popin 85%
}


layerrule {
    name = wlogout
    match:namespace = logout_dialog 
    dim_around = on
    blur = on
    animation = popin 85%
}

layerrule {
    name = swaync-control-center
    match:namespace = swaync-control-center
    blur = on
    animation = slide right 60%
    ignore_alpha = 0.5
    xray = 0
}

layerrule {
    name = swaync-notifications
    match:namespace = swaync-notification-window
    blur = on
    animation = slide right 60%
    ignore_alpha = 0.5
    xray = 0
}

layerrule {
    name = hyprpicker
    match:namespace = hyprpicker
    no_anim = true
    blur = false
}

layerrule {
    name = selection
    match:namespace = selection
    no_anim = true
    blur = false
}
