PACKAGES = [
    "booster", # initcpio generator (faster than mkinitcpio)
    "pipewire", # audio server
    # audio things
    "pipewire-alsa", 
    "pipewire-audio",
    "pipewire-jack",
    "pipewire-pulse",
    "gst-plugin-pipewire",
    "wireplumber",
    "pamixer",
    # gui for pipewire
    "pavucontrol",
    # network manager 
    "networkmanager",
    "network-manager-applet",
    # bluetooth setup
    "bluez",
    "bluez-utils",
    "blueman",
    "brightnessctl",
    "playerctl",
    "udiskie",

    "sddm",
    "qt5-quickcontrols",
    "qt5-quickcontrols2",
    "qt5-graphicaleffects",

    "hyprland",
    "swaync",
    "fuzzel",
    "waybar",
    "awww",
    "eww",
    "hyprlock",
    "wlogout",
    "grim",
    "slurp",
    "cliphist",
    "wl-clip-persist",
    "hyprsunset",

    "polkit-gnome",
    "xdg-desktop-portal-hyprland",
    "xdg-desktop-portal-gtk",
    "xdg-user-dirs",
    "pacman-contrib",
    "parallel",
    "jq",
    "imagemagick",
    "qt5-imageformats",
    "ffmpegthumbs",
    "libnotify",
    "noto-fonts-emoji",

    "kitty",
    "zsh",
    "fzf",
    "tmux",
    "nvim",
    "zoxide",
    "eza",
    "tty-clock",
    "bat",
    "yazi",

    "zen-browser-bin",
    "helium-browser",
    "thunar",
    "file-roller",
    "unzip",
    "nvim",
    "foot",
    "nwg-displays",
]
